.config/nvim/lazy-lock.json
.config/nvim/lua/yyossy/plugins/toggleterm.lua

とりあえず
https://github.com/akinsho/toggleterm.nvim
を導入することで、画面下部にターミナルを出せるようになった

Add toggleterm.lua

---

.config/nvim/lua/yyossy/core/options.lua

close https://github.com/teihenn/dotfiles/issues/21

Change relativenumber to false

---

.tmux.conf
.zshrc
README.md

close https://github.com/teihenn/dotfiles/issues/1

Add other dotfiles

---

.config/nvim/lua/yyossy/core/keymaps.lua

Add keymap for exiting terminal-job mode with <Esc>

---

.config/nvim/lua/yyossy/core/keymaps.lua

Add keymaps for terminal <C-h> and <C-k>

---

README.md
lazygit/config.yml

Add lazygit config

---

.config/nvim/lua/yyossy/plugins/nvim-tree.lua

close https://github.com/teihenn/dotfiles/issues/81

Change open horizontal split keymap of nvim-tree

---

.config/nvim/lua/yyossy/plugins/lualine.lua

Display the breadcrumb trail of the currently open file in lualine

---

.config/nvim/lua/yyossy/plugins/buffer_manager.lua

close https://github.com/teihenn/dotfiles/issues/114

Add buffer_manager keymaps to reorder buffers

---

.config/nvim/lua/yyossy/core/options.lua
.tmux.conf

close https://github.com/teihenn/dotfiles/issues/86

Automatically reload file when it changes outside of Neovim

---

.config/nvim/lua/yyossy/plugins/diffview.lua
.config/nvim/lua/yyossy/plugins/linting.lua

Add diffview.nvim

---

.config/nvim/lua/yyossy/core/keymaps.lua
.config/nvim/lua/yyossy/plugins/toggleterm.lua

close https://github.com/teihenn/dotfiles/issues/119

Cmd line window keymap

---

.config/nvim/lua/yyossy/plugins/telescope.lua

close https://github.com/teihenn/dotfiles/issues/62

Enhance Telescope integration with persistent input for live grep

---

.config/nvim/lua/yyossy/plugins/toggleterm.lua

close https://github.com/teihenn/dotfiles/issues/149

Disable toggleterm

---

Makefile
README.md
setup-sample.log
setup.sh

close https://github.com/teihenn/dotfiles/issues/18

Setup script

---

nvim/lua/yyossy/plugins/markdown-preview.lua

close https://github.com/teihenn/dotfiles/issues/154

Disable auto close of markdown-preview

---

nvim/lua/yyossy/plugins/lsp/lspconfig.lua

close https://github.com/teihenn/dotfiles/issues/126

Enable a keymap to show buffer diagnostics

---

nvim/lua/yyossy/plugins/lsp/lspconfig.lua

fix
- https://github.com/teihenn/dotfiles/issues/159

Add Pyright LSP configuration for improved Python project support

---

tmux/.tmux.conf

close https://github.com/teihenn/dotfiles/issues/158

Change tmux move window keymaps

---

Makefile
README.md
iterm2/colors/everforest_dark_hard.itermcolors
iterm2/config/Profiles.json
iterm2/config/com.googlecode.iterm2.plist
setup.sh

close https://github.com/teihenn/dotfiles/issues/147

Add iterm2

---

iterm2/config/com.googlecode.iterm2.plist
nvim/lazy-lock.json
nvim/lua/yyossy/plugins/colorschema.lua
tmux/.tmux.conf

close https://github.com/teihenn/dotfiles/issues/165

Change to nightfox

---

nvim/lazy-lock.json
nvim/lua/yyossy/plugins/git/gitgraph.lua

close https://github.com/teihenn/dotfiles/issues/101

Add gitgraph

---

nvim/lua/yyossy/plugins/git/gitsigns.lua

close https://github.com/teihenn/dotfiles/issues/170

enable git blame on

---

nvim/lua/yyossy/plugins/git/gitsigns.lua

close https://github.com/teihenn/dotfiles/issues/172

Review gitsigns settings

---

nvim/lazy-lock.json
nvim/lua/yyossy/plugins/git/diffview.lua
nvim/lua/yyossy/plugins/git/gitsigns.lua
nvim/lua/yyossy/plugins/lsp/aerial.lua
zsh/.zshrc

close https://github.com/teihenn/dotfiles/issues/176

Add aerial.nvim

---

zsh/.zshrc

close https://github.com/teihenn/dotfiles/issues/179
- oh-my-zshでプラグイン入れてて手動設定が面倒だったのでoh-my-zshやめるのやめた
- PATHの整理は少しだけした

.zshrcちょっと整理

---

nvim/lua/yyossy/plugins/getlinker.lua

close https://github.com/teihenn/dotfiles/issues/128

Add getlinker.lua

---

nvim/lua/yyossy/plugins/lsp/nvim-cmp.lua

close https://github.com/teihenn/dotfiles/issues/183 https://github.com/teihenn/dotfiles/issues/85

Add luasnip settings for python docstring

---

nvim/lua/yyossy/plugins/lsp/lspconfig.lua
nvim/lua/yyossy/plugins/lsp/mason.lua

close https://github.com/teihenn/dotfiles/issues/143

Add shellcheck and shfmt to mason-tool-installer

---

nvim/lua/yyossy/plugins/lsp/nvim-cmp.lua

close https://github.com/teihenn/dotfiles/issues/202

Add doc snippets

---

README.md
git/.gitconfig
git/.gitconfig.local
setup.sh

close https://github.com/teihenn/dotfiles/issues/198

Add gitconfig

---

iterm2/colors/vscode.itermcolors
iterm2/config/com.googlecode.iterm2.plist
nvim/lazy-lock.json
nvim/lua/yyossy/plugins/colorschema.lua
nvim/lua/yyossy/plugins/lualine.lua

close https://github.com/teihenn/dotfiles/issues/199

Vscode theme

---

nvim/lazy-lock.json
nvim/lua/yyossy/plugins/quicker.lua
nvim/lua/yyossy/plugins/telescope.lua

close https://github.com/teihenn/dotfiles/issues/96

Add quicker.nvim

---

nvim/lua/yyossy/plugins/buffer_manager.lua

close https://github.com/teihenn/dotfiles/issues/213

Config buffer manager

---

README.md
setup.sh

close https://github.com/teihenn/dotfiles/issues/212

.gitconfig.localを$HOMEに配置できるように修正する

---

nvim/lua/yyossy/plugins/buffer_manager.lua

close https://github.com/teihenn/dotfiles/issues/216

Change width of buffer manager

---

nvim/lua/yyossy/plugins/lsp/aerial.lua

close https://github.com/teihenn/dotfiles/issues/218

Disable curly bracket context moving

---

nvim/lua/yyossy/plugins/telescope.lua

close https://github.com/teihenn/dotfiles/issues/206
ファイル検索はfuzzy検索でよいが
文字列検索は完全一致となるようにした

Exact match grep

---

nvim/lua/yyossy/core/keymaps.lua
nvim/lua/yyossy/plugins/ai/avante.lua

close https://github.com/teihenn/dotfiles/issues/188

Add avante.nvim

---

nvim/lua/yyossy/plugins/ai/avante.lua

close https://github.com/yyossy5/dotfiles/issues/233

Disable render-markdown plugin without filetype: Avante

---

Makefile
setup.sh

close https://github.com/yyossy5/dotfiles/issues/240

Setup brew first

---

zsh/.zshrc

close https://github.com/yyossy5/dotfiles/issues/242

Add conda initialize to .zshrc

---

nvim/lua/yyossy/plugins/telescope.lua

close https://github.com/yyossy5/dotfiles/issues/246

Restore telescope live grep behavior

---

nvim/lua/yyossy/plugins/hlslens.lua

close https://github.com/yyossy5/dotfiles/issues/251

Add hlslens.lua

---

lazygit/config.yml

close https://github.com/yyossy5/dotfiles/issues/261
結局リフレッシュ頻度は変えないことにしたが、
今後変えやすいようにデフォルト値で設定だけ追加しておく

Add refresher config to config.yml with default values

---

nvim/lua/yyossy/plugins/lsp/lspconfig.lua

close https://github.com/yyossy5/dotfiles/issues/263
エラーが出なくなったことと、lspで関数定義へジャンプできないなど起きておらず壊れてなさそうなことはさらっと確認した

Update lspconfig.lua for mason-lspconfig v2.x

---

Makefile
setup.sh

close https://github.com/yyossy5/dotfiles/issues/285

Remove wezterm setup

---

nvim/lua/yyossy/plugins/ai/avante.lua

close https://github.com/yyossy5/dotfiles/issues/293

Disable avante.nvim

---

nvim/lua/yyossy/plugins/buffer_manager.lua

close https://github.com/yyossy5/dotfiles/issues/294

Expand buffer manager's width to 150

---

nvim/lua/yyossy/plugins/telescope.lua

close https://github.com/yyossy5/dotfiles/issues/292

Telescope path_display no omitting

---

nvim/lua/yyossy/plugins/telescope.lua

- Expand telescope window to 99% width and 90% height
- Optimize layout with 60% results and 40% preview ratio
- Add horizontal layout strategy for better space utilization
- Include border and dynamic preview title for better UX
- Addresses issue where long file paths were truncated
close https://github.com/yyossy5/dotfiles/issues/338

feat(nvim): improve telescope layout for better file path visibility

---

.claude/settings.local.json
nvim/lua/yyossy/plugins/telescope.lua

close https://github.com/yyossy5/dotfiles/issues/353

Improve telescope

---

Makefile
setup.sh

close https://github.com/yyossy5/dotfiles/issues/362

feat: Gemini CLIのセットアップを追加

---

intellij/.ideavimrc

close https://github.com/yyossy5/dotfiles/issues/360

Improve ideavimrc

---

Makefile
setup.sh

.vrapper自体はすでにコミット済みだったのでsetup.shとMakefileの修正

Update setup.sh and Makefile for vrapper
